# Generated by Django 3.0.5 on 2020-05-25 13:45

from django.db import migrations, models
import indoor_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('indoor_app', '0003_auto_20200524_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=indoor_app.models.upload_path),
        ),
    ]
