# Generated by Django 3.0.5 on 2020-06-14 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indoor_app', '0004_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
    ]
