# Generated by Django 3.0.5 on 2020-07-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoor_app', '0005_auto_20200614_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='detected_objects',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
