# Generated by Django 3.0.5 on 2020-09-03 10:12

from django.db import migrations, models
import indoor_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('indoor_app', '0006_article_detected_objects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AddField(
            model_name='image',
            name='detected_objects',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=indoor_app.models.upload_path),
        ),
    ]
